version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    container_name: code-rag-memgraph
    ports:
      - "7687:7687"  # Bolt protocol
      - "7444:7444"  # HTTP
      - "3000:3000"  # Memgraph Lab
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - memgraph-data:/var/lib/memgraph
      - memgraph-log:/var/log/memgraph
      - memgraph-etc:/etc/memgraph
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:1.22.4
    container_name: code-rag-weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'  # We'll provide our own vectors
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  memgraph-data:
  memgraph-log:
  memgraph-etc:
  weaviate-data: